import pandas as pd

corredorDf = pd.read_csv('corredor.csv', index_col='object')
encruzilhada_direitaDf = pd.read_csv('encruzilhada_direita.csv', index_col='object')
encruzilhada_esquerdaDf = pd.read_csv('encruzilhada_esquerda.csv', index_col='object')
encruzilhada_direita_esquerdaDf = pd.read_csv('encruzilhada_direita_esquerda.csv', index_col='object')
saida_direitaDf = pd.read_csv('saida_direita.csv', index_col='object')
saida_esquerdaDf = pd.read_csv('saida_esquerda.csv', index_col='object')
saida_direita_esquerdaDf = pd.read_csv('saida_direita_esquerda.csv', index_col='object')

corredorDf['label'] = ['corredor'] * len(corredorDf)
encruzilhada_direitaDf['label'] = ['encruzilhada_direita'] * len(encruzilhada_direitaDf)
encruzilhada_esquerdaDf['label'] = ['encruzilhada_esquerda'] * len(encruzilhada_esquerdaDf)
encruzilhada_direita_esquerdaDf['label'] = ['encruzilhada_direita_esquerda'] * len(encruzilhada_direita_esquerdaDf)
saida_direitaDf['label'] = ['saida_direita'] * len(saida_direitaDf)
saida_esquerdaDf['label'] = ['saida_esquerda'] * len(saida_esquerdaDf)
saida_direita_esquerdaDf['label'] = ['saida_direita_esquerda'] * len(saida_direita_esquerdaDf)

dfComplet = corredorDf.append(encruzilhada_direitaDf, ignore_index=True)
dfComplet = dfComplet.append(encruzilhada_direitaDf, ignore_index=True)
dfComplet = dfComplet.append(encruzilhada_esquerdaDf, ignore_index=True)
dfComplet = dfComplet.append(encruzilhada_direita_esquerdaDf, ignore_index=True)
dfComplet = dfComplet.append(saida_direitaDf, ignore_index=True)
dfComplet = dfComplet.append(saida_esquerdaDf, ignore_index=True)
dfComplet = dfComplet.append(saida_direita_esquerdaDf, ignore_index=True)
dfComplet.drop(columns=['0', '180', '181'], inplace=True)
dfComplet.dropna(inplace=True)
print(dfComplet.values)

dfComplet.to_csv('complete.csv')
