import pandas as pd

corredor_1 = pd.read_csv('corredor_1.csv', index_col=0)
corredor_1['label'] = ['corredor_1'] * len(corredor_1)
corredor_2 = pd.read_csv('corredor_2.csv', index_col=0)
corredor_2['label'] = ['corredor_2'] * len(corredor_2)
corredor_3 = pd.read_csv('corredor_3.csv', index_col=0)
corredor_3['label'] = ['corredor_3'] * len(corredor_3)
corredor_4 = pd.read_csv('corredor_4.csv', index_col=0)
corredor_4['label'] = ['corredor_4'] * len(corredor_4)
corredor_5 = pd.read_csv('corredor_5.csv', index_col=0)
corredor_5['label'] = ['corredor_5'] * len(corredor_5)
corredor_6 = pd.read_csv('corredor_6.csv', index_col=0)
corredor_6['label'] = ['corredor_6'] * len(corredor_6)
corredor_7 = pd.read_csv('corredor_7.csv', index_col=0)
corredor_7['label'] = ['corredor_7'] * len(corredor_7)
corredor_8 = pd.read_csv('corredor_8.csv', index_col=0)
corredor_8['label'] = ['corredor_8'] * len(corredor_8)
corredor_9 = pd.read_csv('corredor_9.csv', index_col=0)
corredor_9['label'] = ['corredor_9'] * len(corredor_9)
corredor_10 = pd.read_csv('corredor_10.csv', index_col=0)
corredor_10['label'] = ['corredor_10'] * len(corredor_10)
corredor_11 = pd.read_csv('corredor_11.csv', index_col=0)
corredor_11['label'] = ['corredor_11'] * len(corredor_11)
corredor_12 = pd.read_csv('corredor_12.csv', index_col=0)
corredor_12['label'] = ['corredor_12'] * len(corredor_12)
corredor_13 = pd.read_csv('corredor_13.csv', index_col=0)
corredor_13['label'] = ['corredor_13'] * len(corredor_13)

encruzilhada_1 = pd.read_csv('encruzilhada_1.csv', index_col=0)
encruzilhada_1['label'] = ['encruzilhada_1'] * len(encruzilhada_1)
encruzilhada_2 = pd.read_csv('encruzilhada_2.csv', index_col=0)
encruzilhada_2['label'] = ['encruzilhada_2'] * len(encruzilhada_2)
encruzilhada_3 = pd.read_csv('encruzilhada_3.csv', index_col=0)
encruzilhada_3['label'] = ['encruzilhada_3'] * len(encruzilhada_3)
encruzilhada_4 = pd.read_csv('encruzilhada_4.csv', index_col=0)
encruzilhada_4['label'] = ['encruzilhada_4'] * len(encruzilhada_4)
encruzilhada_5 = pd.read_csv('encruzilhada_5.csv', index_col=0)
encruzilhada_5['label'] = ['encruzilhada_5'] * len(encruzilhada_5)
encruzilhada_6 = pd.read_csv('encruzilhada_6.csv', index_col=0)
encruzilhada_6['label'] = ['encruzilhada_6'] * len(encruzilhada_6)
encruzilhada_7 = pd.read_csv('encruzilhada_7.csv', index_col=0)
encruzilhada_7['label'] = ['encruzilhada_7'] * len(encruzilhada_7)
encruzilhada_8 = pd.read_csv('encruzilhada_8.csv', index_col=0)
encruzilhada_8['label'] = ['encruzilhada_8'] * len(encruzilhada_8)
encruzilhada_9 = pd.read_csv('encruzilhada_9.csv', index_col=0)
encruzilhada_9['label'] = ['encruzilhada_9'] * len(encruzilhada_9)
encruzilhada_10 = pd.read_csv('encruzilhada_10.csv', index_col=0)
encruzilhada_10['label'] = ['encruzilhada_10'] * len(encruzilhada_10)

encruzilhada_direita_1 = pd.read_csv('encruzilhada_direita_1.csv', index_col=0)
encruzilhada_direita_1['label'] = ['encruzilhada_direita_1'] * len(encruzilhada_direita_1)
encruzilhada_direita_2 = pd.read_csv('encruzilhada_direita_2.csv', index_col=0)
encruzilhada_direita_2['label'] = ['encruzilhada_direita_2'] * len(encruzilhada_direita_2)
encruzilhada_direita_3 = pd.read_csv('encruzilhada_direita_3.csv', index_col=0)
encruzilhada_direita_3['label'] = ['encruzilhada_direita_3'] * len(encruzilhada_direita_3)
encruzilhada_direita_4 = pd.read_csv('encruzilhada_direita_4.csv', index_col=0)
encruzilhada_direita_4['label'] = ['encruzilhada_direita_4'] * len(encruzilhada_direita_4)
encruzilhada_direita_5 = pd.read_csv('encruzilhada_direita_5.csv', index_col=0)
encruzilhada_direita_5['label'] = ['encruzilhada_direita_5'] * len(encruzilhada_direita_5)
encruzilhada_direita_6 = pd.read_csv('encruzilhada_direita_6.csv', index_col=0)
encruzilhada_direita_6['label'] = ['encruzilhada_direita_6'] * len(encruzilhada_direita_6)
encruzilhada_direita_7 = pd.read_csv('encruzilhada_direita_7.csv', index_col=0)
encruzilhada_direita_7['label'] = ['encruzilhada_direita_7'] * len(encruzilhada_direita_7)
encruzilhada_direita_8 = pd.read_csv('encruzilhada_direita_8.csv', index_col=0)
encruzilhada_direita_8['label'] = ['encruzilhada_direita_8'] * len(encruzilhada_direita_8)
encruzilhada_direita_9 = pd.read_csv('encruzilhada_direita_9.csv', index_col=0)
encruzilhada_direita_9['label'] = ['encruzilhada_direita_9'] * len(encruzilhada_direita_9)
encruzilhada_direita_10 = pd.read_csv('encruzilhada_direita_10.csv', index_col=0)
encruzilhada_direita_10['label'] = ['encruzilhada_direita_10'] * len(encruzilhada_direita_10)

encruzilhada_esquerda_1 = pd.read_csv('encruzilhada_esquerda_1.csv', index_col=0)
encruzilhada_esquerda_1['label'] = ['encruzilhada_esquerda_1'] * len(encruzilhada_esquerda_1)
encruzilhada_esquerda_2 = pd.read_csv('encruzilhada_esquerda_2.csv', index_col=0)
encruzilhada_esquerda_2['label'] = ['encruzilhada_esquerda_2'] * len(encruzilhada_esquerda_2)
encruzilhada_esquerda_3 = pd.read_csv('encruzilhada_esquerda_3.csv', index_col=0)
encruzilhada_esquerda_3['label'] = ['encruzilhada_esquerda_3'] * len(encruzilhada_esquerda_3)
encruzilhada_esquerda_4 = pd.read_csv('encruzilhada_esquerda_4.csv', index_col=0)
encruzilhada_esquerda_4['label'] = ['encruzilhada_esquerda_4'] * len(encruzilhada_esquerda_4)
encruzilhada_esquerda_5 = pd.read_csv('encruzilhada_esquerda_5.csv', index_col=0)
encruzilhada_esquerda_5['label'] = ['encruzilhada_esquerda_5'] * len(encruzilhada_esquerda_5)
encruzilhada_esquerda_6 = pd.read_csv('encruzilhada_esquerda_6.csv', index_col=0)
encruzilhada_esquerda_6['label'] = ['encruzilhada_esquerda_6'] * len(encruzilhada_esquerda_6)
encruzilhada_esquerda_7 = pd.read_csv('encruzilhada_esquerda_7.csv', index_col=0)
encruzilhada_esquerda_7['label'] = ['encruzilhada_esquerda_7'] * len(encruzilhada_esquerda_7)
encruzilhada_esquerda_8 = pd.read_csv('encruzilhada_esquerda_8.csv', index_col=0)
encruzilhada_esquerda_8['label'] = ['encruzilhada_esquerda_8'] * len(encruzilhada_esquerda_8)
encruzilhada_esquerda_9 = pd.read_csv('encruzilhada_esquerda_9.csv', index_col=0)
encruzilhada_esquerda_9['label'] = ['encruzilhada_esquerda_9'] * len(encruzilhada_esquerda_9)
encruzilhada_esquerda_10 = pd.read_csv('encruzilhada_esquerda_10.csv', index_col=0)
encruzilhada_esquerda_10['label'] = ['encruzilhada_esquerda_10'] * len(encruzilhada_esquerda_10)

saida_direita_1 = pd.read_csv('saida_direita_1.csv', index_col=0)
saida_direita_1['label'] = ['saida_direita_1'] * len(saida_direita_1)

saida_esquerda_1 = pd.read_csv('saida_esquerda_1.csv', index_col=0)
saida_esquerda_1['label'] = ['saida_esquerda_1'] * len(saida_esquerda_1)

saida_direita_esquerda_1 = pd.read_csv('saida_direita_esquerda_1.csv', index_col=0)
saida_direita_esquerda_1['label'] = ['saida_direita_esquerda_1'] * len(saida_direita_esquerda_1)

lista_corredor = [corredor_1, corredor_2, corredor_3, corredor_4, corredor_5, corredor_6, corredor_7, corredor_8, corredor_9, corredor_10, corredor_11, corredor_12, corredor_13]
lista_encruzilhada = [encruzilhada_1, encruzilhada_2, encruzilhada_3, encruzilhada_4, encruzilhada_5, encruzilhada_6, encruzilhada_7, encruzilhada_8,encruzilhada_9, encruzilhada_10]
lista_encruzilhada_direita = [encruzilhada_direita_1, encruzilhada_direita_2, encruzilhada_direita_3, encruzilhada_direita_4, encruzilhada_direita_5, encruzilhada_direita_6, encruzilhada_direita_7, encruzilhada_direita_8, encruzilhada_direita_9, encruzilhada_direita_10]
lista_encruzilhada_esquerda = [encruzilhada_esquerda_1, encruzilhada_esquerda_2, encruzilhada_esquerda_3, encruzilhada_esquerda_4, encruzilhada_esquerda_5, encruzilhada_esquerda_6, encruzilhada_esquerda_7, encruzilhada_esquerda_8, encruzilhada_esquerda_9, encruzilhada_esquerda_10]
lista_saida_direita = [saida_direita_1]
lista_saida_esquerda = [saida_esquerda_1]
lista_saida_direita_esquerda = [saida_direita_esquerda_1]

lista = lista_corredor + lista_encruzilhada
rangeImageCompleteDf = pd.DataFrame()
rangeImageCompleteDf = pd.concat(lista, ignore_index=True)
rangeImageCompleteDf.index.name = 'object'
rangeImageCompleteDf.to_csv('complete2.csv')
